# Generated by Django 3.0.5 on 2022-04-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
